# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Sheet Music"
  pageRef = "sheet"
  weight = 10

[[main]]
  name = "About Me"
  pageRef = "intro"
  weight = 15

[[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@mufu-composer?sub_confirmation=1"
  weight = 200 

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/mufu.composer/reels/"
  weight = 400


[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ramandrosoa"
  weight = 400

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://linkedin.com/in/minah-ramandrosoa-023490245"
  weight = 400 


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 #[[footer]]
 #  name = "Authors"
 #  pageRef = "authors"
 #  weight = 20
